name: 'Eran Pal '
favicon: null
layout_spectrum: 0.49729
typography_spectrum: 0.50052
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030207'
    - '#2a2522'
    - '#8f8166'
    - '#a19c88'
    - '#6b5c45'
  brandStrength: 0
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
